/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TestApiRouteImport } from './routes/test-api'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as DriverRouteRouteImport } from './routes/driver/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserProductsRouteImport } from './routes/user/products'
import { Route as UserOrdersRouteImport } from './routes/user/orders'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as ProductsCartRouteImport } from './routes/products/cart'
import { Route as PaymentPaystackRouteImport } from './routes/payment/paystack'
import { Route as LocationsLocationsRouteImport } from './routes/locations/locations'
import { Route as DriverProfileRouteImport } from './routes/driver/profile'
import { Route as DriverOrdersRouteImport } from './routes/driver/orders'
import { Route as DriverDriverRouteImport } from './routes/driver/driver'
import { Route as DriverDeliveriesRouteImport } from './routes/driver/deliveries'
import { Route as DriverDashboardRouteImport } from './routes/driver/dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as UserSettingsProfileRouteImport } from './routes/user/settings/profile'
import { Route as AdminSettingsProfileRouteImport } from './routes/admin/settings/profile'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TestApiRoute = TestApiRouteImport.update({
  id: '/test-api',
  path: '/test-api',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRouteRoute = DriverRouteRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserProductsRoute = UserProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserOrdersRoute = UserOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRouteRoute,
} as any)
const ProductsCartRoute = ProductsCartRouteImport.update({
  id: '/products/cart',
  path: '/products/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPaystackRoute = PaymentPaystackRouteImport.update({
  id: '/payment/paystack',
  path: '/payment/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationsRoute = LocationsLocationsRouteImport.update({
  id: '/locations/locations',
  path: '/locations/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverOrdersRoute = DriverOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverDriverRoute = DriverDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverDeliveriesRoute = DriverDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DriverRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const UserSettingsProfileRoute = UserSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminSettingsProfileRoute = AdminSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/driver': typeof DriverRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signin': typeof SigninRoute
  '/test-api': typeof TestApiRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/driver': typeof DriverDriverRoute
  '/driver/orders': typeof DriverOrdersRoute
  '/driver/profile': typeof DriverProfileRoute
  '/locations/locations': typeof LocationsLocationsRoute
  '/payment/paystack': typeof PaymentPaystackRoute
  '/products/cart': typeof ProductsCartRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/orders': typeof UserOrdersRoute
  '/user/products': typeof UserProductsRoute
  '/admin/': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/user/settings/profile': typeof UserSettingsProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/driver': typeof DriverRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signin': typeof SigninRoute
  '/test-api': typeof TestApiRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/driver': typeof DriverDriverRoute
  '/driver/orders': typeof DriverOrdersRoute
  '/driver/profile': typeof DriverProfileRoute
  '/locations/locations': typeof LocationsLocationsRoute
  '/payment/paystack': typeof PaymentPaystackRoute
  '/products/cart': typeof ProductsCartRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/orders': typeof UserOrdersRoute
  '/user/products': typeof UserProductsRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/user/settings/profile': typeof UserSettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/driver': typeof DriverRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signin': typeof SigninRoute
  '/test-api': typeof TestApiRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/driver': typeof DriverDriverRoute
  '/driver/orders': typeof DriverOrdersRoute
  '/driver/profile': typeof DriverProfileRoute
  '/locations/locations': typeof LocationsLocationsRoute
  '/payment/paystack': typeof PaymentPaystackRoute
  '/products/cart': typeof ProductsCartRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/orders': typeof UserOrdersRoute
  '/user/products': typeof UserProductsRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/user/settings/profile': typeof UserSettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/driver'
    | '/user'
    | '/about'
    | '/admin'
    | '/contact'
    | '/contacts'
    | '/dashboard'
    | '/login'
    | '/signin'
    | '/test-api'
    | '/testimonials'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/driver/dashboard'
    | '/driver/deliveries'
    | '/driver/driver'
    | '/driver/orders'
    | '/driver/profile'
    | '/locations/locations'
    | '/payment/paystack'
    | '/products/cart'
    | '/user/dashboard'
    | '/user/orders'
    | '/user/products'
    | '/admin/'
    | '/products'
    | '/admin/settings/profile'
    | '/user/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/driver'
    | '/user'
    | '/about'
    | '/contact'
    | '/contacts'
    | '/dashboard'
    | '/login'
    | '/signin'
    | '/test-api'
    | '/testimonials'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/driver/dashboard'
    | '/driver/deliveries'
    | '/driver/driver'
    | '/driver/orders'
    | '/driver/profile'
    | '/locations/locations'
    | '/payment/paystack'
    | '/products/cart'
    | '/user/dashboard'
    | '/user/orders'
    | '/user/products'
    | '/admin'
    | '/products'
    | '/admin/settings/profile'
    | '/user/settings/profile'
  id:
    | '__root__'
    | '/'
    | '/driver'
    | '/user'
    | '/about'
    | '/admin'
    | '/contact'
    | '/contacts'
    | '/dashboard'
    | '/login'
    | '/signin'
    | '/test-api'
    | '/testimonials'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/driver/dashboard'
    | '/driver/deliveries'
    | '/driver/driver'
    | '/driver/orders'
    | '/driver/profile'
    | '/locations/locations'
    | '/payment/paystack'
    | '/products/cart'
    | '/user/dashboard'
    | '/user/orders'
    | '/user/products'
    | '/admin/'
    | '/products/'
    | '/admin/settings/profile'
    | '/user/settings/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriverRouteRoute: typeof DriverRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SigninRoute: typeof SigninRoute
  TestApiRoute: typeof TestApiRoute
  TestimonialsRoute: typeof TestimonialsRoute
  LocationsLocationsRoute: typeof LocationsLocationsRoute
  PaymentPaystackRoute: typeof PaymentPaystackRoute
  ProductsCartRoute: typeof ProductsCartRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-api': {
      id: '/test-api'
      path: '/test-api'
      fullPath: '/test-api'
      preLoaderRoute: typeof TestApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/products': {
      id: '/user/products'
      path: '/products'
      fullPath: '/user/products'
      preLoaderRoute: typeof UserProductsRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/orders': {
      id: '/user/orders'
      path: '/orders'
      fullPath: '/user/orders'
      preLoaderRoute: typeof UserOrdersRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/products/cart': {
      id: '/products/cart'
      path: '/products/cart'
      fullPath: '/products/cart'
      preLoaderRoute: typeof ProductsCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/paystack': {
      id: '/payment/paystack'
      path: '/payment/paystack'
      fullPath: '/payment/paystack'
      preLoaderRoute: typeof PaymentPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/locations': {
      id: '/locations/locations'
      path: '/locations/locations'
      fullPath: '/locations/locations'
      preLoaderRoute: typeof LocationsLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/orders': {
      id: '/driver/orders'
      path: '/orders'
      fullPath: '/driver/orders'
      preLoaderRoute: typeof DriverOrdersRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/driver': {
      id: '/driver/driver'
      path: '/driver'
      fullPath: '/driver/driver'
      preLoaderRoute: typeof DriverDriverRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/deliveries': {
      id: '/driver/deliveries'
      path: '/deliveries'
      fullPath: '/driver/deliveries'
      preLoaderRoute: typeof DriverDeliveriesRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/settings/profile': {
      id: '/user/settings/profile'
      path: '/settings/profile'
      fullPath: '/user/settings/profile'
      preLoaderRoute: typeof UserSettingsProfileRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/admin/settings/profile': {
      id: '/admin/settings/profile'
      path: '/settings/profile'
      fullPath: '/admin/settings/profile'
      preLoaderRoute: typeof AdminSettingsProfileRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface DriverRouteRouteChildren {
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverDeliveriesRoute: typeof DriverDeliveriesRoute
  DriverDriverRoute: typeof DriverDriverRoute
  DriverOrdersRoute: typeof DriverOrdersRoute
  DriverProfileRoute: typeof DriverProfileRoute
}

const DriverRouteRouteChildren: DriverRouteRouteChildren = {
  DriverDashboardRoute: DriverDashboardRoute,
  DriverDeliveriesRoute: DriverDeliveriesRoute,
  DriverDriverRoute: DriverDriverRoute,
  DriverOrdersRoute: DriverOrdersRoute,
  DriverProfileRoute: DriverProfileRoute,
}

const DriverRouteRouteWithChildren = DriverRouteRoute._addFileChildren(
  DriverRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserOrdersRoute: typeof UserOrdersRoute
  UserProductsRoute: typeof UserProductsRoute
  UserSettingsProfileRoute: typeof UserSettingsProfileRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserOrdersRoute: UserOrdersRoute,
  UserProductsRoute: UserProductsRoute,
  UserSettingsProfileRoute: UserSettingsProfileRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSettingsProfileRoute: typeof AdminSettingsProfileRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSettingsProfileRoute: AdminSettingsProfileRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriverRouteRoute: DriverRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SigninRoute: SigninRoute,
  TestApiRoute: TestApiRoute,
  TestimonialsRoute: TestimonialsRoute,
  LocationsLocationsRoute: LocationsLocationsRoute,
  PaymentPaystackRoute: PaymentPaystackRoute,
  ProductsCartRoute: ProductsCartRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
